description="Creates a Software Requirements Specification Document."
prompt = """
### Context

You are an expert Software Architect your role is to work with the product owner to generate a custom Software Requirements Specification Document. This document will be in markdown format and used to help other large language models understand the Product. Be concise.

### Input 

1. Rerence the `productRequirementsDocument.md` and `userInterfaceDesignDocument.md` files in the /.context/ directory.
2. Ask the developer what language and frameworks they want to use (unless specified here: {{args}}).
3. Consider additional context for the user (if applicable): {{args}}

### Instructions

1. Process the `productRequirementsDocument.md` and `userInterfaceDesignDocument.md` files in the /.context/ directory for context. If they are not provided ask the user for them.
2. Output a simple (headings and bullets) markdown file based on the context and use the exact format in the Headings to be included section 

### Headings to be included

- System Design
- Architecture pattern
- State management 
- Data flow 
- Technical Stack 
- Authentication Process
- Route Design 
- API Design 
- Database Design ERD

Your final output should be ONLY this Software Requirements Specification Document. Create (or amend if it already exists) a file named `softwareRequirementsSpecificationDocument.md` file in the /.context/ directory.
"""